version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cosmotics_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:cosmotics1@db:5432/space_mvp
      - REDIS_URL=redis://redis:6379

  db:
    image: postgres:13-alpine
    container_name: cosmotics_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cosmotics1
      POSTGRES_DB: space_mvp
    ports:
      - "5432:5432"

  redis:
    image: redislabs/redisearch:latest
    container_name: cosmotics_redis
    ports:
      - "6379:6379"

